name: MKFormeller LLC CI/CD

on:
  push:
    branches:
      - "main"

defaults:
  run:
    working-directory: client

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies, run tests and build
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm i
          npm run build --if-present
      - name: Upload build folder to artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: client/build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build folder from artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1" # optional: defaults to us-east-1
          # SOURCE_DIR: "build" # optional: defaults to entire repository
